package com.yeoboya.com.yeoboya_Q;



public class MainConstant
{
  public static final String API_KEY = "AIzaSyBFEpTQktnx5qtZpwlCSqicGhx8MRmqrps";
  public static final String APP_ID_BuzzAd = "127171392177226";
  public static final String ENCODE_UTF8 = "UTF-8";
  public static final String FUNC_JS_NATIVE_API = "callFromWeb";
  public static final String FUNC_JS_NATIVE_FILE = "fileChooserFromWeb";
  public static final String FUNC_NATIVE_JS = "$.webScript";
  public static final String HMSG_ALARM_MSG = "alarmMsg";
  public static final String HMSG_PUSH_MESSAGE = "pushMessage";
  public static final String HMSG_PUSH_NOTINUM = "pushType";
  public static boolean IS_DEBUGGING = false;
  public static boolean IS_EASTER_EGG = false;
  public static boolean IS_FORCE_STORE = false;
  public static boolean IS_IMG_RESIZING = false;
  public static boolean IS_ONESTORE = false;
  public static final boolean IS_ONESTORE_RELEASE = true;
  public static final String MARKET_YEOBOYA = "market://details?id=com.yeoboya.com.yeoboya";
  public static final int MSG_CALL_FINISH = 20063;
  public static final int MSG_GO_INQUERY = 20052;
  public static final int MSG_HANDLE_GCMID_RECV = 20004;
  public static final int MSG_HANDLE_NATIVE_WEB_SCRIPT = 20001;
  public static final int MSG_HANDLE_NATIVE_WEB_SMS = 20003;
  public static final int MSG_HANDLE_SESSION_RECV = 20005;
  public static final int MSG_HIDE_SPLASH = 20064;
  public static final int MSG_JS_CMD_ALL_LIST = 20035;
  public static final int MSG_JS_CMD_AUTO_LOGIN = 20019;
  public static final int MSG_JS_CMD_C2DM_ID = 20010;
  public static final int MSG_JS_CMD_CHATSVR_INFO = 20024;
  public static final int MSG_JS_CMD_CHATSVR_IS_CONNT = 20025;
  public static final int MSG_JS_CMD_CHATSVR_LOGIN = 20021;
  public static final int MSG_JS_CMD_CHATSVR_LOGIN_FAIL = 20022;
  public static final int MSG_JS_CMD_CHATSVR_SEND_MSG = 20023;
  public static final int MSG_JS_CMD_FINISH_APP = 20013;
  public static final int MSG_JS_CMD_FINISH_POPUP = 20029;
  public static final int MSG_JS_CMD_HANDLE_DATA = 20060;
  public static final int MSG_JS_CMD_INAPP_BILL = 20017;
  public static final int MSG_JS_CMD_ITEM_BUY = 20032;
  public static final int MSG_JS_CMD_KAKAO_LINK = 20016;
  public static final int MSG_JS_CMD_LGOIN_FAIL = 20020;
  public static final int MSG_JS_CMD_MAINWEB_REFRESH = 20028;
  public static final int MSG_JS_CMD_MSG_BOX = 20033;
  public static final int MSG_JS_CMD_PAY_PURCHASE = 20055;
  public static final int MSG_JS_CMD_PLAY_BEEP = 20018;
  public static final int MSG_JS_CMD_REFRESH_WEB = 20056;
  public static final int MSG_JS_CMD_SATAE_LOGIN = 20026;
  public static final int MSG_JS_CMD_SATAE_LOGIN_WAIT = 20027;
  public static final int MSG_JS_CMD_SHOW_IMAGE = 20015;
  public static final int MSG_JS_CMD_SHOW_MENUBAR = 20030;
  public static final int MSG_JS_CMD_WEB_LOGIN = 20011;
  public static final int MSG_JS_CMD_WEB_LOGOUT = 20012;
  public static final int MSG_JS_CMD_WEB_PAY = 20014;
  public static final int MSG_JS_CMD_WRITE_VIEW = 20034;
  public static final int MSG_MAKE_ANI_GIF = 20069;
  public static final int MSG_MAKE_ANI_ING = 20070;
  public static final int MSG_MOVE_URL = 80;
  public static final int MSG_ONESTORE_ALERT = 20041;
  public static final int MSG_ONESTORE_CONFIRM = 20042;
  public static final int MSG_ONESTORE_INFO = 20040;
  public static final int MSG_PAGER_WAIT = 20002;
  public static final int MSG_RING_START_STOP = 83;
  public static final int MSG_SHOW_USERINFO = 20062;
  public static final int MSG_SOCIAL_LOGIN = 20053;
  public static final int MSG_TIMEOUT_PROCESS = 20036;
  public static final int MSG_VIDEOCHAT_REDIRECT = 20051;
  public static final int MSG_VIDEO_ALLOW = 82;
  public static final int MSG_VIDEO_CALL_ME = 73;
  public static final int MSG_VIDEO_INTRO = 81;
  public static final int MSG_VIDEO_NICK_DEL = 74;
  public static final int MSG_VIDEO_PHO_DEL = 75;
  public static final int MSG_VIDEO_REFRESH = 84;
  public static final int MSG_VIDEO_REFUSE = 72;
  public static final int MSG_VIDEO_REQUEST = 71;
  public static final int MSG_WIN_SIZE = 20054;
  public static final String OAUTH_CLIENT_ID = "dw83cQhYdeyDThtPiKru";
  public static final String OAUTH_CLIENT_NAME = "여보야";
  public static final String OAUTH_CLIENT_SECRET = "1b_0ZjxFH5";
  public static final String OAUTH_LOGIN_FACEBOOK = "facebook";
  public static final String OAUTH_LOGIN_KAKAO = "kakao";
  public static final String OAUTH_LOGIN_NAVER = "naver";
  public static final String PROJECT_ID = "447792266631";
  public static final int PUSHMSG_TO_WEBSCRIPT = 20061;
  public static final String RESOURCE_YEOBOYA = "android.resource://com.yeoboya.com.yeoboya/";
  public static final int SET_DEVICE_TOKEN = 20066;
  public static final int SMSMSG_TO_WEBSCRIPT = 20065;
  public static final String TEXT_GOTO_APP_YEOBOYA = "앱으로 이동";
  public static String URL_AUTH_PHONE;
  public static String URL_DEBUG_MAIN;
  public static String URL_FOREIGN;
  public static String URL_IMAGEVIEW;
  public static String URL_ITEM_BUY;
  public static String URL_JOINUS;
  public static String URL_LOGIN;
  public static String URL_MAIN;
  public static String URL_MSGBOX;
  public static String URL_UPGRADE;
  public static String URL_UPLOAD_FILE;
  public static String URL_USEROUT;
  public static String URL_VCHAT_ASK_PHP;
  public static String URL_WARNNING;
  public static String URL_WRITEVIEW;
  public static final boolean USE_BASE64_DECODE = true;
  public static String WEBADDR_YEOBOYA;
  public static final String imgKakaoLink = "http://image.yeoboya.com/imgs/new_wedding/mobile/img/kakao_img_02.png";
  public static String url_call_cookie;
  public static String url_call_proc_msg;
  public static String url_call_sess_addr;
  public static String url_call_sess_real;
  public static String url_call_sess_state;
  public static String url_call_sess_test;
  public static String url_call_splash_msg;

  static
  {
    IS_DEBUGGING = false;
    IS_IMG_RESIZING = true;
    URL_DEBUG_MAIN = "http://devm-minismart.yeoboya.com";
    IS_FORCE_STORE = true;
    IS_ONESTORE = false;
    WEBADDR_YEOBOYA = "http://m.yeoboya.com";
    URL_MAIN = "http://m.yeoboya.com/";
    URL_LOGIN = "http://m.yeoboya.com/";
    URL_JOINUS = "https://secure.yeoboya.com/regist/registMember.html";
    URL_AUTH_PHONE = "https://secure.yeoboya.com/regist/registCheck.html?directCall=";
    URL_MSGBOX = "http://m.yeoboya.com/";
    URL_WRITEVIEW = "http://m.yeoboya.com/";
    URL_IMAGEVIEW = "http://m.yeoboya.com/?chnl=cont&ctrl=photoview&dest=single&type=msg&";
    URL_USEROUT = "http://m.yeoboya.com/?chnl=cont&ctrl=alert&dest=index";
    URL_WARNNING = "http://m.yeoboya.com/?chnl=cont&ctrl=alert&dest=index";
    URL_UPGRADE = "http://m.yeoboya.com/?chnl=cont&ctrl=member&dest=appUpdate";
    URL_FOREIGN = "http://m.yeoboya.com/?chnl=cont&ctrl=member&dest=logout";
    URL_UPLOAD_FILE = "http://photo.yeoboya.com/prg/yeo_photo/yeo_upload_multi.php";
    URL_ITEM_BUY = "https://pay.yeoboya.com/type/inAppPay/index.php";
    url_call_splash_msg = "http://m.yeoboya.com/cont/intro/spMsg.php";
    url_call_proc_msg = "http://m.yeoboya.com/api/index.php";
    url_call_sess_state = "http://m.yeoboya.com/ajax/getDbDomainCode.php";
    url_call_sess_addr = "http://ses.yeoboya.com:7401/";
    url_call_sess_real = "http://ses.yeoboya.com:7401/";
    url_call_sess_test = "http://devsol4.yeoboya.com:7401/";
    url_call_cookie = "";
    URL_VCHAT_ASK_PHP = "http://m.yeoboya.com/api/index.php";
  }

  public static void changeMainUrl(String paramString)
  {
    WEBADDR_YEOBOYA = paramString + "";
    URL_MAIN = paramString + "/";
    URL_LOGIN = paramString + "/";
    URL_MSGBOX = paramString + "/";
    URL_WRITEVIEW = paramString + "/";
    URL_IMAGEVIEW = paramString + "/?chnl=cont&ctrl=photoview&dest=single&type=msg&";
    URL_USEROUT = paramString + "/?chnl=cont&ctrl=alert&dest=index";
    URL_WARNNING = paramString + "/?chnl=cont&ctrl=alert&dest=index";
    URL_UPGRADE = paramString + "/?chnl=cont&ctrl=member&dest=appUpdate";
    URL_FOREIGN = paramString + "/?chnl=cont&ctrl=member&dest=logout";
    url_call_splash_msg = paramString + "/cont/intro/spMsg.php";
    url_call_proc_msg = paramString + "/api/index.php";
    url_call_sess_state = paramString + "/ajax/getDbDomainCode.php";
    URL_VCHAT_ASK_PHP = paramString + "/api/index.php";
  }
}
